/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define IOPCEN_BIT			4U

#define RCC_BASE_ADDR		0x40021000
#define RCC_APB2ENR_OFFSET	0x18
#define RCC_APB2ENR			(RCC_BASE_ADDR + RCC_APB2ENR_OFFSET)

#define GPIOC_BASE_ADDR		0x40011000
#define GPIOx_CRH_OFFSET	0x04
#define GPIOC_CRH			(GPIOC_BASE_ADDR + GPIOx_CRH_OFFSET)
#define GPIOx_BSRR_OFFSET	0x10
#define GPIOC_BSRR			(GPIOC_BASE_ADDR + GPIOx_BSRR_OFFSET)
#define GPIOx_BRR_OFFSET	0x14
#define GPIOC_BRR			(GPIOC_BASE_ADDR + GPIOx_BRR_OFFSET)

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void delay(uint32_t tick){
	for(int i = 0U; i < tick; ++i);
}

int main(void)
{
	// Enable RCC to generate the clock
	*(uint32_t*)RCC_APB2ENR |= (1U << IOPCEN_BIT);

	// Set Mode for PC13, PC14
	*(uint32_t*)GPIOC_CRH &= ~(0xFU << 20U);
	*(uint32_t*)GPIOC_CRH |= (0x2U << 20U);

    /* Loop forever */
	for(;;)
	{
		// Turn OFF LED
		*(uint32_t*)GPIOC_BSRR |= (0x1U << 13U);
		delay(1000);

		// Turn ON LED
		*(uint32_t*)GPIOC_BSRR |= (0x1U << 29U);
		delay(1000);
	}
}
