/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "stm32f411xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{

#if 0 && PULL_PUSH
	GPIO_PinConfig_t pin = {
			GPIO_PIN_NO_12,
			GPIO_MODE_OUT,
			GPIO_SPEED_LOW,
			GPIO_NO_PUPD,
			GPIO_OP_TYPE_PP,
			GPIO_ALT_FN_AF0
	};
	GPIO_Handle_t pGPIOHandle = {GPIOD, pin};

	GPIO_PeriClockControl(GPIOD, ENABLE);

	GPIO_Init(&pGPIOHandle);

    /* Loop forever */
	for(;;){
		GPIO_ToggleOutputPin(GPIOD, pin.GPIO_PinNumber);
		for(uint32_t i = 0 ; i < 500U*1250U ; i++);

	}
#endif

	GPIO_PinConfig_t pin_10 = {
			GPIO_PIN_NO_10,
			GPIO_MODE_OUT,
			GPIO_SPEED_LOW,
			GPIO_NO_PUPD,
			GPIO_OP_TYPE_OD,
			GPIO_ALT_FN_AF0
	};
	GPIO_Handle_t pGPIOHandle = {GPIOD, pin_10};

	GPIO_PeriClockControl(GPIOD, ENABLE);

	GPIO_Init(&pGPIOHandle);

    /* Loop forever */
	for(;;){
		GPIO_ToggleOutputPin(GPIOD, pin_10.GPIO_PinNumber);
		for(uint32_t i = 0 ; i < 500U*1250U ; i++);

	}

}
