/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "stm32f411xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
#if 0 && INTERNAL_LED_AND_BUTTON
	GPIO_PinConfig_t pin_PA0 = {
			GPIO_PIN_NO_0,
			GPIO_MODE_IN,
			0,
			0,
			0,
			0
	};
	GPIO_Handle_t GPIO_A_Handle = {GPIOA, pin_PA0};

	// Set up for PA0 pin
	GPIO_PeriClockControl(GPIOA, ENABLE);
	GPIO_Init(&GPIO_A_Handle);

	GPIO_PinConfig_t pin_PD12 = {
			GPIO_PIN_NO_12,
			GPIO_MODE_OUT,
			GPIO_SPEED_LOW,
			GPIO_NO_PUPD,
			GPIO_OP_TYPE_PP,
			GPIO_ALT_FN_AF0
	};
	GPIO_Handle_t GPIO_D_Handle = {GPIOD, pin_PD12};

	GPIO_PeriClockControl(GPIOD, ENABLE);
	GPIO_Init(&GPIO_D_Handle);

    /* Loop forever */
	for(;;){
		if(GPIO_ReadFromInputPin(GPIOA, GPIO_A_Handle.GPIO_PinConfig.GPIO_PinNumber)){
			GPIO_WriteToOutputPin(GPIOD, GPIO_D_Handle.GPIO_PinConfig.GPIO_PinNumber, SET);
		}
		{
			GPIO_WriteToOutputPin(GPIOD, GPIO_D_Handle.GPIO_PinConfig.GPIO_PinNumber, RESET);
		}
	}
#endif
	//BUTTON
	GPIO_PinConfig_t pin_PB12 = {
			GPIO_PIN_NO_12,
			GPIO_MODE_IN,
			0,
			GPIO_PIN_PD,
			0,
			0
	};
	GPIO_Handle_t GPIO_B_Handle = {GPIOB, pin_PB12};

	// Set up for PB12 pin
	GPIO_PeriClockControl(GPIOB, ENABLE);
	GPIO_Init(&GPIO_B_Handle);


	//LED
	GPIO_PinConfig_t pin_PA5 = {
			GPIO_PIN_NO_5,
			GPIO_MODE_OUT,
			0,
			0,
			GPIO_OP_TYPE_PP,
			0
	};
	GPIO_Handle_t GPIO_A_Handle = {GPIOA, pin_PA5};

	GPIO_PeriClockControl(GPIOA, ENABLE);
	GPIO_Init(&GPIO_A_Handle);


	GPIO_PinConfig_t pin_PD12 = {
			GPIO_PIN_NO_12,
			GPIO_MODE_OUT,
			GPIO_SPEED_LOW,
			GPIO_NO_PUPD,
			GPIO_OP_TYPE_PP,
			GPIO_ALT_FN_AF0
	};
	GPIO_Handle_t GPIO_D_Handle = {GPIOD, pin_PD12};

	GPIO_PeriClockControl(GPIOD, ENABLE);
	GPIO_Init(&GPIO_D_Handle);

    /* Loop forever */
	for(;;){
		if(GPIO_ReadFromInputPin(GPIOB, GPIO_B_Handle.GPIO_PinConfig.GPIO_PinNumber)){
			GPIO_WriteToOutputPin(GPIOA, GPIO_A_Handle.GPIO_PinConfig.GPIO_PinNumber, SET);
//			GPIO_WriteToOutputPin(GPIOD, GPIO_D_Handle.GPIO_PinConfig.GPIO_PinNumber, SET);
		}
		{
			GPIO_WriteToOutputPin(GPIOA, GPIO_A_Handle.GPIO_PinConfig.GPIO_PinNumber, RESET);
			GPIO_WriteToOutputPin(GPIOD, GPIO_D_Handle.GPIO_PinConfig.GPIO_PinNumber, RESET);
		}
	}
}
