/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

//#include "stm32f411xx.h"
#include "stm32f411xx_gpio_driver.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{

	GPIO_PinConfig_t pin = {
			GPIO_PIN_NO_5,
			GPIO_MODE_ALTFN,
			GPIO_SPEED_FAST,
			0,
			0,
			GPIO_ALT_FN_AF5
	};
	GPIO_Handle_t pGPIOHandle = {GPIOB, pin};

	GPIO_PeriClockControl(GPIOB, ENABLE);

	GPIO_Init(&pGPIOHandle);

	GPIO_DeInit(GPIOB);

    /* Loop forever */
	for(;;);
}
